spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: bpms
    password: password

keycloak:
  url: http://localhost:8200
  system-user:
    realm: test-realm
    client-id: client-id
    client-secret: client-secret

digital-document-service:
  url: http://localhost:8201